apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-deployment
  namespace: customerservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customerservice
        image: sabafadhl/customerservice:latest
        ports:
        - containerPort: 8080
