apiVersion: v1
kind: Service
metadata:
  name: customerservice-service
  namespace: customerservice
  labels:
    app: customer-app
spec: # Specifies the specification of the Service, including its selector and ports.
  selector: # Specifies how the Service identifies which Pods to target.
    app: customer-app # Selects Pods with the label app=my-app
  type: LoadBalancer
  ports:
    - protocol: TCP #Specifies the protocol used for the port (TCP or UDP).
      port: 9090 # Specifies the port number on the Service itself.
      targetPort: 8080 #Specifies the port number on the Pods targeted by the Service.