# This workflow will build a .NET project
name: .NET

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore CustomerService/CustomerService.csproj
    - name: Build
      run: dotnet build CustomerService/CustomerService.csproj --no-restore
    - name: Test
      run: dotnet test CustomerService/CustomerService.csproj --no-build --verbosity normal
